# -*- coding: utf-8 -*-
"""financial-reasoning-llm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hp6a2yEeMrzy9hogENo3ywtai_Uwk3B6
"""

!pip install transformers datasets peft accelerate

import random, math, json

def sharpe_example():
    r1, v1 = random.uniform(0.05, 0.25), random.uniform(0.05, 0.30)
    r2, v2 = random.uniform(0.05, 0.25), random.uniform(0.05, 0.30)
    s1, s2 = r1 / v1, r2 / v2
    better = "Strategy A" if s1 > s2 else "Strategy B"
    return f"Question: Returns {r1:.2%}, {r2:.2%} with vol {v1:.2%}, {v2:.2%}\nReasoning: Sharpe A={s1:.2f}, B={s2:.2f}\nConclusion: {better}"

def compounding_example():
    r = random.uniform(0.01, 0.05)
    years = random.randint(2, 10)
    growth = (1 + r) ** years
    return f"Question: {r:.2%} for {years} years\nReasoning: (1+r)^n ≈ {growth:.2f}\nConclusion: {growth:.2f}x"

def drawdown_example():
    peak = random.uniform(100, 200)
    trough = peak * random.uniform(0.6, 0.95)
    dd = (trough - peak) / peak
    return f"Question: {peak:.0f} to {trough:.0f}\nReasoning: dd ≈ {dd:.2%}\nConclusion: {dd:.2%}"

GENERATORS = [sharpe_example, compounding_example, drawdown_example]

data = []
for gen in GENERATORS:
    for _ in range(100):
        data.append({"text": gen()})

random.shuffle(data)

with open("dataset.jsonl", "w") as f:
    for d in data:
        f.write(json.dumps(d) + "\n")

print("✅ Dataset created")

from transformers import DataCollatorForLanguageModeling
import json, random

with open("dataset.jsonl") as f:
    data = [json.loads(l) for l in f]

random.shuffle(data)

split = int(0.9 * len(data))
train = data[:split]
val = data[split:]

with open("train.jsonl", "w") as f:
    for x in train:
        f.write(json.dumps(x) + "\n")

with open("val.jsonl", "w") as f:
    for x in val:
        f.write(json.dumps(x) + "\n")

print("✅ Split done")

import os
print(os.listdir())

from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer
from datasets import load_dataset
from peft import LoraConfig, get_peft_model
import torch

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

dataset = load_dataset("json", data_files={
    "train": "train.jsonl",
    "validation": "val.jsonl"
})

def tokenize(example):
    tokens = tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )
    tokens["labels"] = tokens["input_ids"].copy()
    return tokens

dataset = dataset.map(tokenize)

model = AutoModelForCausalLM.from_pretrained(model_name)

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.05,
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)

training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=4,
    num_train_epochs=1,
    learning_rate=2e-4,
    logging_steps=10,
    fp16=True
)

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)
trainer = Trainer(
    model=model,
    train_dataset=dataset["train"],
    eval_dataset=dataset["validation"],
    args=training_args,
    data_collator=data_collator   # ADD THIS LINE
)
trainer.train()

model.save_pretrained("lora_model")

print("✅ TRAINING DONE")

from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained("lora_model").to("cuda")

print("Model loaded successfully!")

from transformers import AutoTokenizer, AutoModelForCausalLM
import json
import torch

# Device setup
device = "cuda" if torch.cuda.is_available() else "cpu"

# Load model + tokenizer
model = AutoModelForCausalLM.from_pretrained("lora_model").to(device)
tokenizer = AutoTokenizer.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0")

model.eval()

# Generate function
def generate(prompt):
    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=100
        )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)


# 🔥 Extract conclusion function
def extract_conclusion(text):
    if "Conclusion:" in text:
        return text.split("Conclusion:")[-1].strip()
    return ""


# 🔥 Check numeric presence
def has_number(text):
    return any(char.isdigit() for char in text)


# Evaluation
correct = 0
total = 0

with open("val.jsonl") as f:
    for i, line in enumerate(f):
        sample = json.loads(line)
        text = sample["text"]

        # Get question
        question = text.split("Reasoning:")[0]

        # Ground truth + prediction
        ground_truth = extract_conclusion(text)
        output = generate(question)
        predicted = extract_conclusion(output)

        print("\n==============================")
        print("QUESTION:", question)
        print("GROUND TRUTH:", ground_truth)
        print("MODEL OUTPUT:", predicted)

        # 🔥 FINAL METRIC (strong)
        if (
            "Conclusion:" in output and
            has_number(predicted) and
            ground_truth[:5] in predicted
        ):
            correct += 1

        total += 1

        if i == 9:  # evaluate 10 samples
            break

print(f"\n✅ Final Score: {correct}/{total}")

import json

new_data = []

with open("dataset.jsonl") as f:
    for line in f:
        sample = json.loads(line)
        text = sample["text"]

        # Extract parts
        question = text.split("Reasoning:")[0]
        conclusion = text.split("Conclusion:")[-1]

        # New format (NO reasoning)
        new_text = question + "Conclusion: " + conclusion

        new_data.append({"text": new_text})

# Save new dataset
with open("dataset_no_reasoning.jsonl", "w") as f:
    for d in new_data:
        f.write(json.dumps(d) + "\n")

print("✅ New dataset created")

import random

with open("dataset_no_reasoning.jsonl") as f:
    data = [json.loads(l) for l in f]

random.shuffle(data)

split = int(0.9 * len(data))

train = data[:split]
val = data[split:]

with open("train_no_reasoning.jsonl", "w") as f:
    for x in train:
        f.write(json.dumps(x) + "\n")

with open("val_no_reasoning.jsonl", "w") as f:
    for x in val:
        f.write(json.dumps(x) + "\n")

print("✅ Split done")

dataset = load_dataset("json", data_files={
    "train": "train_no_reasoning.jsonl",
    "validation": "val_no_reasoning.jsonl"
})

model.save_pretrained("lora_model_no_reasoning")

from transformers import AutoTokenizer, AutoModelForCausalLM
import json
import torch

# Load model (NO reasoning version)
device = "cuda" if torch.cuda.is_available() else "cpu"

model = AutoModelForCausalLM.from_pretrained("lora_model_no_reasoning").to(device)
tokenizer = AutoTokenizer.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0")

model.eval()

# Generate function
def generate(prompt):
    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=100
        )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)


# Extract conclusion
def extract_conclusion(text):
    if "Conclusion:" in text:
        return text.split("Conclusion:")[-1].strip()
    return ""


# Check numeric presence
def has_number(text):
    return any(char.isdigit() for char in text)


# Evaluation
correct = 0
total = 0

with open("val_no_reasoning.jsonl") as f:
    for i, line in enumerate(f):
        sample = json.loads(line)
        text = sample["text"]

        # Extract question (NO reasoning dataset still starts with Question)
        question = text.split("Conclusion:")[0]

        # Ground truth
        ground_truth = extract_conclusion(text)

        # Model prediction
        output = generate(question)
        predicted = extract_conclusion(output)

        print("\n==============================")
        print("QUESTION:", question)
        print("GROUND TRUTH:", ground_truth)
        print("MODEL OUTPUT:", predicted)

        # Final metric
        if (
            "Conclusion:" in output and
            has_number(predicted) and
            ground_truth[:5] in predicted
        ):
            correct += 1

        total += 1

        if i == 9:  # evaluate 10 samples
            break

print(f"\n✅ Final Score (No Reasoning Model): {correct}/{total}")

from google.colab import files

files.download("train.jsonl")
files.download("val.jsonl")
files.download("dataset.jsonl")